[package]
name = "lang"
version = "0.1.0"
authors = ["flyingcanoe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift-simplejit = "0.64.0"
cranelift = "0.64.0"
cranelift-module = "0.64.0"